DocumentSettings ignore extra fields Pydantic Validation
When setting the default pydantic Config to forbig extra fields:

```py
from pydantic import config, Extra
config.BaseConfig.extra = Extra.forbid
```

Beanie throws errors at document initialization due to the following:
ValidationError: 4 validation errors for DocumentSettings
__dict__
  extra fields not permitted (type=value_error.extra)
__doc__
  extra fields not permitted (type=value_error.extra)
__module__
  extra fields not permitted (type=value_error.extra)
__weakref__
  extra fields not permitted (type=value_error.extra)


The proposed commit fixes the issue. 
Not sure if ideal, or if there is any caveats with this solution